# Generated by Django 2.0.2 on 2018-03-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.IntegerField()),
                ('home_number', models.IntegerField()),
                ('work_number', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('notes', models.TextField(max_length=500)),
            ],
        ),
    ]
